---

- name: Install packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - git
    - htop
    - python-software-properties
    - curl
    - unzip
    - ntp
    - python-pip

- name: install docker-py with pip
  pip: name=docker-py
