---

- name: run mysql container
  docker_container:
    name: mysql
    image: mysql:latest
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

- name: run wordpress container
  docker_container:
    name: wordpress
    image: wordpress:latest
    state: started
    restart_policy: always
    ports:
      - 8080:80
    links:
      - mysql:mysql
    env:
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
